# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d80b3ffc72307b116bb4298328a9530c53f9951442bb42e7536a0f53fde474c9bcf765f9db169ed541d5c0be72bda5ea14ea084326a05f6ac83573c916724b

test:
  secret_key_base: 957428163a03935c5f644a569ccfa93c8bb549f3d832f3ba71f664187a9f99fb4860080bd6db7628af2fc0a2cf8e4c5e3102d277cdad62c003fd98986139ed5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
